---
name: Semantic Versionning Bumper Syntax Checks

on:
  workflow_call:

permissions: read-all

jobs:
  syntax:
    name: Syntax
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Commitlint
        uses: wagoid/commitlint-github-action@v5
        with:
          failOnWarnings: true

      - name: Install YAMLlint PyLint, Flake8 And Black
        run: pip install --user yamllint pylint flake8 black

      - name: Run YAMLlint
        run: yamllint --strict .

      - name: Run Flake8
        run: |
          # Stop the build if there are Python syntax errors or undefined names
          flake8 --max-line-length=88 --select=E9,F63,F7,F82 --show-source --statistics .

          # Run Flake8 (The GitHub editor is 127 chars wide)
          flake8 --max-line-length=88 --statistics .

          # Exit-zero treats all complexity errors as warnings
          flake8 --max-line-length=88 --exit-zero --max-complexity=10 .

      - name: Run PyLint
        id: pylint
        run: pylint --disable=F0401 *.py

      - name: Run Black
        run: black --check --diff --color .
